-- Add missing numerology interpretations for all topics

-- Momento Decisivo interpretations
INSERT INTO conteudos_numerologia (topico, conteudo) VALUES 
('momento_decisivo', '{
  "1": "**Número 1 no Momento Decisivo**: Este é um período de novos começos e liderança. Você está sendo chamado a tomar iniciativa e confiar em sua capacidade de abrir novos caminhos. É hora de assumir o comando de sua vida e não depender dos outros para as decisões importantes.",
  "2": "**Número 2 no Momento Decisivo**: Este momento pede cooperação e paciência. Você precisará trabalhar em equipe e buscar harmonia nas relações. As decisões devem ser tomadas considerando o bem-estar de todos os envolvidos. Evite pressa e cultive a diplomacia.",
  "3": "**Número 3 no Momento Decisivo**: É um período de expressão criativa e comunicação. Suas ideias e talentos artísticos ganham destaque. Use sua criatividade para resolver problemas e se expressar de forma autêntica. A comunicação clara será essencial.",
  "4": "**Número 4 no Momento Decisivo**: Este momento exige disciplina, organização e trabalho árduo. É hora de construir bases sólidas para o futuro. Planejamento detalhado e persistência serão suas ferramentas principais. Evite atalhos e foque na qualidade.",
  "5": "**Número 5 no Momento Decisivo**: Um período de mudanças e aventuras. Você será chamado a sair da zona de conforto e explorar novas possibilidades. Liberdade e variedade são importantes agora. Esteja aberto a experiências diferentes.",
  "6": "**Número 6 no Momento Decisivo**: Este momento foca em responsabilidades familiares e comunitárias. Você pode ser chamado a cuidar de outros ou assumir responsabilidades domésticas. O amor, a cura e o serviço aos outros são temas centrais.",
  "7": "**Número 7 no Momento Decisivo**: É um período de introspecção e busca espiritual. Você precisa de tempo para reflexão e análise profunda. A intuição e a sabedoria interior serão seus guias. Evite decisões precipitadas e busque conhecimento.",
  "8": "**Número 8 no Momento Decisivo**: Este momento traz foco no sucesso material e reconhecimento. Questões financeiras e de carreira ganham destaque. Use sua ambição de forma equilibrada e ética. O poder deve ser exercido com responsabilidade.",
  "9": "**Número 9 no Momento Decisivo**: Um período de conclusão e serviço humanitário. Você pode precisar deixar ir situações ou relacionamentos que já cumpriram seu propósito. Foque em causas maiores e no bem da humanidade.",
  "11": "**Número 11 no Momento Decisivo**: Este é um momento de alta inspiração e intuição. Você pode receber insights profundos que transformam sua vida. Use sua sensibilidade psíquica de forma construtiva. Evite a tendência ao nervosismo e mantenha-se centrado.",
  "22": "**Número 22 no Momento Decisivo**: Um período de realização de grandes projetos e sonhos. Você tem o potencial de criar algo duradouro que beneficie muitas pessoas. Combine visão com praticidade. Este é um momento de construção em grande escala."
}');

-- Anjo da Guarda interpretations  
INSERT INTO conteudos_numerologia (topico, conteudo) VALUES 
('anjo_guarda', '{
  "Vehuiah": "**Anjo Vehuiah (21/03 a 25/03)**: Anjo da vontade e da transformação. Traz força para superar obstáculos e iniciar novos projetos. Ajuda na liderança e na coragem para enfrentar desafios.",
  "Jeliel": "**Anjo Jeliel (26/03 a 30/03)**: Anjo do amor e da sabedoria. Promove relacionamentos harmoniosos e ajuda a resolver conflitos. Traz paz interior e compreensão mútua.",
  "Sitael": "**Anjo Sitael (31/03 a 04/04)**: Anjo da construção e da perseverança. Ajuda na realização de projetos a longo prazo e no desenvolvimento da paciência necessária para o sucesso.",
  "Elemiah": "**Anjo Elemiah (05/04 a 09/04)**: Anjo da proteção e da cura. Oferece proteção contra energias negativas e ajuda nos processos de cura física e emocional.",
  "Mahasiah": "**Anjo Mahasiah (10/04 a 14/04)**: Anjo da harmonia e da reconciliação. Promove a paz e ajuda na resolução de conflitos familiares e profissionais.",
  "Lelahel": "**Anjo Lelahel (15/04 a 20/04)**: Anjo da cura e da saúde. Especializa-se em cura física e emocional, trazendo vitalidade e bem-estar.",
  "Achaiah": "**Anjo Achaiah (21/04 a 25/04)**: Anjo da paciência e da descoberta. Ajuda na compreensão de mistérios e no desenvolvimento da intuição.",
  "Cahetel": "**Anjo Cahetel (26/04 a 30/04)**: Anjo da proteção divina e da bênção. Oferece proteção especial e ajuda na conexão com o divino.",
  "Haziel": "**Anjo Haziel (01/05 a 05/05)**: Anjo do perdão e da misericórdia divina. Ajuda no processo de perdão e na liberação de ressentimentos.",
  "Aladiah": "**Anjo Aladiah (06/05 a 10/05)**: Anjo da cura e da renovação. Especializa-se em processos de renovação e regeneração em todas as áreas da vida.",
  "Lauviah": "**Anjo Lauviah (11/05 a 15/05)**: Anjo da vitória e da fama. Ajuda na conquista de objetivos e no reconhecimento pelo trabalho realizado.",
  "Hahaiah": "**Anjo Hahaiah (16/05 a 20/05)**: Anjo da proteção e do refúgio. Oferece proteção em momentos difíceis e ajuda a encontrar refúgio seguro.",
  "Iezalel": "**Anjo Iezalel (21/05 a 25/05)**: Anjo da fidelidade e da reconciliação. Promove relacionamentos duradouros e ajuda na resolução de desentendimentos.",
  "Mebahel": "**Anjo Mebahel (26/05 a 31/05)**: Anjo da verdade e da liberdade. Ajuda na busca da verdade e na libertação de situações opressivas.",
  "Hariel": "**Anjo Hariel (01/06 a 05/06)**: Anjo da purificação e da renovação. Especializa-se em processos de limpeza espiritual e renovação interior.",
  "Hekamiah": "**Anjo Hekamiah (06/06 a 10/06)**: Anjo da lealdade e da amizade. Promove relacionamentos leais e duradouros, especialmente amizades.",
  "Lauviah": "**Anjo Lauviah (11/06 a 15/06)**: Anjo da revelação e da inspiração. Traz insights e revelações importantes para o crescimento espiritual.",
  "Caliel": "**Anjo Caliel (16/06 a 21/06)**: Anjo da justiça divina. Ajuda a fazer justiça e a corrigir injustiças, promovendo a equidade.",
  "Leuviah": "**Anjo Leuviah (22/06 a 26/06)**: Anjo da inteligência e da memória. Desenvolve capacidades intelectuais e ajuda na retenção de conhecimento.",
  "Pahaliah": "**Anjo Pahaliah (27/06 a 01/07)**: Anjo da castidade e da pureza. Promove relacionamentos puros e ajuda na manutenção da integridade moral.",
  "Nelchael": "**Anjo Nelchael (02/07 a 06/07)**: Anjo da proteção contra calúnias. Oferece proteção contra fofocas e maledicências.",
  "Yeiayel": "**Anjo Yeiayel (07/07 a 11/07)**: Anjo da fama e da fortuna. Ajuda na conquista de reconhecimento e sucesso material.",
  "Melahel": "**Anjo Melahel (12/07 a 16/07)**: Anjo da cura das águas. Especializa-se em cura através dos elementos da natureza.",
  "Hahiuiah": "**Anjo Hahiuiah (17/07 a 22/07)**: Anjo da proteção e do refúgio. Oferece proteção especial e ajuda a encontrar segurança.",
  "Nith-Haiah": "**Anjo Nith-Haiah (23/07 a 27/07)**: Anjo da sabedoria e da magia branca. Desenvolve capacidades psíquicas e intuição.",
  "Haaiah": "**Anjo Haaiah (28/07 a 01/08)**: Anjo da política e da diplomacia. Ajuda em negociações e na resolução de conflitos políticos.",
  "Yeratel": "**Anjo Yeratel (02/08 a 06/08)**: Anjo da propagação da luz. Ajuda na disseminação de conhecimento e luz espiritual.",
  "Seheiah": "**Anjo Seheiah (07/08 a 12/08)**: Anjo da longevidade e da saúde. Promove vida longa e saúde duradoura.",
  "Reiyel": "**Anjo Reiyel (13/08 a 17/08)**: Anjo da libertação. Ajuda na libertação de situações opressivas e limitantes.",
  "Omael": "**Anjo Omael (18/08 a 22/08)**: Anjo da paciência e da fertilidade. Desenvolve paciência e ajuda em questões de fertilidade.",
  "Lecabel": "**Anjo Lecabel (23/08 a 28/08)**: Anjo da inteligência e das decisões. Ajuda na tomada de decisões sábias e no desenvolvimento intelectual.",
  "Vasariah": "**Anjo Vasariah (29/08 a 02/09)**: Anjo da justiça e da clemência. Promove justiça equilibrada com misericórdia.",
  "Iehuiah": "**Anjo Iehuiah (03/09 a 07/09)**: Anjo da obediência e da subordinação. Ensina a importância da humildade e obediência às leis divinas.",
  "Lehahiah": "**Anjo Lehahiah (08/09 a 12/09)**: Anjo da obediência e da calma. Promove tranquilidade e ensina a importância da obediência.",
  "Chavakiah": "**Anjo Chavakiah (13/09 a 17/09)**: Anjo da reconciliação. Especializa-se em reconciliar diferenças e promover harmonia.",
  "Menadel": "**Anjo Menadel (18/09 a 23/09)**: Anjo do trabalho e da vocação. Ajuda a descobrir e desenvolver a verdadeira vocação profissional.",
  "Aniel": "**Anjo Aniel (24/09 a 28/09)**: Anjo da vitória e da coragem. Dá coragem para enfrentar desafios e alcançar vitórias.",
  "Haamiah": "**Anjo Haamiah (29/09 a 03/10)**: Anjo dos rituais e cerimônias religiosas. Ajuda em práticas espirituais e rituais sagrados.",
  "Rehael": "**Anjo Rehael (04/10 a 08/10)**: Anjo da cura familiar. Especializa-se em cura de relacionamentos familiares e filiais.",
  "Ieiazel": "**Anjo Ieiazel (09/10 a 13/10)**: Anjo da alegria e da consolação. Traz alegria e consolo em momentos de tristeza.",
  "Hahahel": "**Anjo Hahahel (14/10 a 18/10)**: Anjo da espiritualidade e da missão. Ajuda a descobrir e cumprir a missão espiritual de vida.",
  "Mikael": "**Anjo Mikael (19/10 a 23/10)**: Anjo da proteção e da força. Oferece proteção poderosa e força para superar obstáculos.",
  "Veualiah": "**Anjo Veualiah (24/10 a 28/10)**: Anjo da prosperidade. Ajuda na conquista de prosperidade material e espiritual.",
  "Yelahiah": "**Anjo Yelahiah (29/10 a 02/11)**: Anjo da proteção em batalhas. Oferece proteção em conflitos e competições.",
  "Sealiah": "**Anjo Sealiah (03/11 a 07/11)**: Anjo da motivação e da vontade. Desenvolve motivação e força de vontade para alcançar objetivos.",
  "Ariel": "**Anjo Ariel (08/11 a 12/11)**: Anjo da revelação e da percepção. Traz revelações importantes e desenvolve percepção espiritual.",
  "Asaliah": "**Anjo Asaliah (13/11 a 17/11)**: Anjo da contemplação e da justiça. Promove contemplação profunda e senso de justiça.",
  "Mihael": "**Anjo Mihael (18/11 a 22/11)**: Anjo da fertilidade e da fidelidade conjugal. Ajuda em questões de fertilidade e harmonia conjugal.",
  "Vehuel": "**Anjo Vehuel (23/11 a 27/11)**: Anjo da elevação e da grandeza. Ajuda na elevação espiritual e conquista de grandes objetivos.",
  "Daniel": "**Anjo Daniel (28/11 a 02/12)**: Anjo da eloquência e da misericórdia. Desenvolve capacidades de comunicação e compaixão.",
  "Hahasiah": "**Anjo Hahasiah (03/12 a 07/12)**: Anjo da medicina universal. Especializa-se em cura holística e medicina natural.",
  "Imamiah": "**Anjo Imamiah (08/12 a 12/12)**: Anjo da liberdade e da proteção dos prisioneiros. Ajuda na libertação de situações limitantes.",
  "Nanael": "**Anjo Nanael (13/12 a 16/12)**: Anjo da comunicação espiritual. Facilita a comunicação com o mundo espiritual e desenvolve mediunidade.",
  "Nithael": "**Anjo Nithael (17/12 a 21/12)**: Anjo da juventude eterna e da beleza. Promove vitalidade e preservação da juventude.",
  "Mebahiah": "**Anjo Mebahiah (22/12 a 26/12)**: Anjo da moralidade e da religião. Desenvolve senso moral e fortalece a fé religiosa.",
  "Poyel": "**Anjo Poyel (27/12 a 31/12)**: Anjo da fortuna e do sucesso. Atrai boa sorte e sucesso em empreendimentos.",
  "Nemamiah": "**Anjo Nemamiah (01/01 a 05/01)**: Anjo da prosperidade e da liderança. Desenvolve capacidades de liderança e atrai prosperidade.",
  "Ieialel": "**Anjo Ieialel (06/01 a 10/01)**: Anjo da cura mental. Especializa-se em cura de distúrbios mentais e emocionais.",
  "Harahel": "**Anjo Harahel (11/01 a 15/01)**: Anjo da riqueza intelectual. Desenvolve capacidades intelectuais e conhecimento.",
  "Mitzrael": "**Anjo Mitzrael (16/01 a 20/01)**: Anjo da reparação e da cura. Ajuda na reparação de danos e processos de cura.",
  "Umabel": "**Anjo Umabel (21/01 a 25/01)**: Anjo da amizade e da afinidade. Promove amizades verdadeiras e relacionamentos afins.",
  "Iah-Hel": "**Anjo Iah-Hel (26/01 a 30/01)**: Anjo do desejo de conhecer. Desenvolve sede de conhecimento e sabedoria.",
  "Anauel": "**Anjo Anauel (31/01 a 04/02)**: Anjo da saúde e da proteção comercial. Protege negócios e promove saúde física.",
  "Mehiel": "**Anjo Mehiel (05/02 a 09/02)**: Anjo da vivificação e da fecundidade. Promove vida e fertilidade em todas as áreas.",
  "Damabiah": "**Anjo Damabiah (10/02 a 14/02)**: Anjo da sabedoria e da fonte de sabedoria. Desenvolve sabedoria profunda e discernimento.",
  "Manakel": "**Anjo Manakel (15/02 a 19/02)**: Anjo do conhecimento do bem e do mal. Desenvolve discernimento moral e ético.",
  "Eyael": "**Anjo Eyael (20/02 a 24/02)**: Anjo da longevidade e da consolação. Promove vida longa e oferece consolo em dificuldades.",
  "Habuhiah": "**Anjo Habuhiah (25/02 a 29/02)**: Anjo da cura e da saúde. Especializa-se em cura de doenças e promoção da saúde.",
  "Rochel": "**Anjo Rochel (01/03 a 05/03)**: Anjo da restituição. Ajuda na recuperação de coisas perdidas e na justiça reparadora.",
  "Jabamiah": "**Anjo Jabamiah (06/03 a 10/03)**: Anjo da regeneração. Promove renovação e regeneração em todos os aspectos da vida.",
  "Haiaiel": "**Anjo Haiaiel (11/03 a 15/03)**: Anjo da proteção e da coragem. Oferece proteção divina e desenvolve coragem interior.",
  "Mumiah": "**Anjo Mumiah (16/03 a 20/03)**: Anjo dos finais e renascimentos. Ajuda em processos de finalização e novos começos."
}');

-- Ciclos de Vida interpretations
INSERT INTO conteudos_numerologia (topico, conteudo) VALUES 
('ciclos_vida', '{
  "1": "**Ciclo de Vida 1**: Período de independência e liderança. Você desenvolve sua individualidade e aprende a confiar em si mesmo. É um tempo de novos começos e iniciativas pessoais.",
  "2": "**Ciclo de Vida 2**: Período de cooperação e relacionamentos. Você aprende sobre parceria, diplomacia e trabalho em equipe. Relacionamentos e harmonia são temas centrais.",
  "3": "**Ciclo de Vida 3**: Período de expressão criativa e comunicação. Você desenvolve seus talentos artísticos e habilidades de comunicação. Criatividade e autoexpressão são enfatizadas.",
  "4": "**Ciclo de Vida 4**: Período de trabalho árduo e construção. Você aprende sobre disciplina, organização e perseverança. É um tempo de estabelecer bases sólidas.",
  "5": "**Ciclo de Vida 5**: Período de liberdade e aventura. Você busca variedade, mudança e novas experiências. Viagens e exploração são temas importantes.",
  "6": "**Ciclo de Vida 6**: Período de responsabilidade familiar e serviço. Você se foca em casa, família e comunidade. Cuidado e responsabilidade são centrais.",
  "7": "**Ciclo de Vida 7**: Período de introspecção e crescimento espiritual. Você busca conhecimento profundo e desenvolvimento interior. Espiritualidade e análise são temas principais.",
  "8": "**Ciclo de Vida 8**: Período de conquista material e reconhecimento. Você foca em carreira, finanças e autoridade. Sucesso material e poder são enfatizados.",
  "9": "**Ciclo de Vida 9**: Período de serviço humanitário e sabedoria. Você se dedica a causas maiores e compartilha sua sabedoria. Compaixão e serviço são centrais.",
  "11": "**Ciclo de Vida 11**: Período de inspiração e intuição elevada. Você desenvolve capacidades psíquicas e espirituais. Inspiração e iluminação são temas principais.",
  "22": "**Ciclo de Vida 22**: Período de realização de grandes projetos. Você tem o potencial de criar algo duradouro e significativo. Construção em grande escala é o foco."
}')